# Generated by Django 5.2.3 on 2025-06-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockOHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
            options={
                'db_table': 'stock_ohlcv',
                'ordering': ['ticker', 'date'],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'date'), name='unique_ticker_date')],
            },
        ),
    ]
