# Generated by Django 5.2.3 on 2025-06-20 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockOHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('change', models.FloatField(default=0.0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv', to='myweb.company')),
            ],
            options={
                'db_table': 'stock_ohlcv',
                'ordering': ['code', 'date'],
                'constraints': [models.UniqueConstraint(fields=('code', 'date'), name='unique_code_date')],
            },
        ),
    ]
