# Generated by Django 5.2.3 on 2025-06-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ma50', models.FloatField(default=0.0)),
                ('ma150', models.FloatField(default=0.0)),
                ('ma200', models.FloatField(default=0.0)),
                ('rsScore', models.FloatField(default=0.0)),
                ('rsScore1m', models.FloatField(default=0.0)),
                ('rsScore3m', models.FloatField(default=0.0)),
                ('rsScore6m', models.FloatField(default=0.0)),
                ('rsScore12m', models.FloatField(default=0.0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='myweb.company')),
            ],
            options={
                'db_table': 'stock_analysis',
                'ordering': ['code', 'date'],
                'constraints': [models.UniqueConstraint(fields=('code', 'date'), name='uniqueAnalysis_code_date')],
            },
        ),
    ]
