# Generated by Django 5.2.3 on 2025-06-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=200)),
                ('listing_date', models.DateField()),
                ('settle_month', models.CharField(max_length=10)),
                ('representative', models.CharField(max_length=100)),
                ('homepage', models.URLField()),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
