# Generated by Django 5.2.3 on 2025-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_stockanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='rsRank',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsRank12m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsRank1m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsRank3m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsRank6m',
            field=models.FloatField(default=0.0),
        ),
    ]
