# Generated by Django 5.2.3 on 2025-06-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='company',
            name='listing_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='region',
        ),
        migrations.RemoveField(
            model_name='company',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='company',
            name='settle_month',
        ),
    ]
