# Generated by Django 5.2.3 on 2025-06-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_stockanalysis_rsrank_stockanalysis_rsrank12m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='max_52w',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='max_52w_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='min_52w',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='min_52w_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
