# Generated by Django 5.2.3 on 2025-06-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_stockanalysis_max_52w_stockanalysis_max_52w_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='is_minervini_trend',
            field=models.BooleanField(default=False),
        ),
    ]
