# Generated by Django 5.2.3 on 2025-06-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_stockanalysis_is_minervini_trend'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('quarter', models.CharField(max_length=3)),
                ('statement_type', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=20)),
                ('amount', models.BigIntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='myweb.company')),
            ],
            options={
                'db_table': 'stock_financial',
                'ordering': ['year', 'quarter'],
                'constraints': [models.UniqueConstraint(fields=('code', 'year', 'quarter'), name='uniqueFinancial_code_year_quarter')],
            },
        ),
    ]
