# Generated by Django 5.2.3 on 2025-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_stockfinancialstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfinancialstatement',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
