# Generated by Django 5.2.3 on 2025-07-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_alter_tradingconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingconfig',
            old_name='position_size',
            new_name='entry_point',
        ),
    ]
