# Generated by Django 5.2.3 on 2025-06-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_alter_stockfinancialstatement_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockfinancialstatement',
            name='uniqueFinancial_code_year_quarter',
        ),
        migrations.AddConstraint(
            model_name='stockfinancialstatement',
            constraint=models.UniqueConstraint(fields=('code', 'year', 'quarter', 'statement_type', 'account_name'), name='uniqueFinancial_code_year_quarter'),
        ),
    ]
