# Generated by Django 5.2.3 on 2025-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_rename_position_size_tradingconfig_entry_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfig',
            name='positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='pyramiding_entries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
