# Generated by Django 5.2.3 on 2025-06-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_remove_stockfinancialstatement_uniquefinancial_code_year_quarter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockanalysis',
            name='rsRank12m',
        ),
        migrations.RemoveField(
            model_name='stockanalysis',
            name='rsRank1m',
        ),
        migrations.RemoveField(
            model_name='stockanalysis',
            name='rsRank3m',
        ),
        migrations.RemoveField(
            model_name='stockanalysis',
            name='rsRank6m',
        ),
        migrations.RemoveField(
            model_name='stockanalysis',
            name='rsScore12m',
        ),
        migrations.RemoveField(
            model_name='stockanalysis',
            name='rsScore1m',
        ),
        migrations.RemoveField(
            model_name='stockanalysis',
            name='rsScore3m',
        ),
        migrations.RemoveField(
            model_name='stockanalysis',
            name='rsScore6m',
        ),
    ]
