# Generated by Django 5.2.3 on 2025-07-27 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_add_50d_fields_to_stock_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_trading_mode', models.CharField(choices=[('manual', 'Manual'), ('turtle', 'Turtle(ATR)')], default='turtle', max_length=20)),
                ('default_strategy_type', models.CharField(choices=[('mtt', 'MTT (Minervini Trend Template)'), ('weekly_high', '52주 신고가')], default='mtt', max_length=20)),
                ('default_max_loss', models.FloatField(default=8.0)),
                ('default_stop_loss', models.FloatField(default=2.0)),
                ('default_take_profit', models.FloatField(blank=True, null=True)),
                ('default_pyramiding_count', models.IntegerField(default=3)),
                ('default_position_size', models.FloatField(default=25.0)),
                ('default_entry_trigger', models.FloatField(default=1.0)),
                ('default_exit_trigger', models.FloatField(default=2.0)),
                ('use_trailing_stop', models.BooleanField(default=True)),
                ('trailing_stop_percent', models.FloatField(default=3.0)),
                ('trading_start_time', models.TimeField(default='09:00')),
                ('trading_end_time', models.TimeField(default='15:30')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_defaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '자동매매 기본값 설정',
                'verbose_name_plural': '자동매매 기본값 설정들',
            },
        ),
    ]
