# Generated by Django 5.2.3 on 2025-07-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_remove_stockanalysis_rsrank12m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='rsRank12m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsRank1m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsRank3m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsRank6m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsScore12m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsScore1m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsScore3m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rsScore6m',
            field=models.FloatField(default=0.0),
        ),
    ]
