# Generated by Django 5.2.3 on 2025-07-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0010_stockanalysis_rsrank12m_stockanalysis_rsrank1m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='atr',
            field=models.FloatField(default=0.0),
        ),
    ]
