# Generated by Django 5.2.3 on 2025-07-02 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_stockanalysis_atr'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndex',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='myweb.stockindex'),
        ),
    ]
