# Generated by Django 5.2.3 on 2025-07-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0012_stockindex_company_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='index',
        ),
        migrations.AddField(
            model_name='company',
            name='indices',
            field=models.ManyToManyField(related_name='companies', to='myweb.stockindex'),
        ),
    ]
