# Generated by Django 5.2.3 on 2025-07-03 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0013_remove_company_index_company_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexOHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_ohlcv', to='myweb.stockindex')),
            ],
            options={
                'db_table': 'index_ohlcv',
                'ordering': ['code', 'date'],
                'constraints': [models.UniqueConstraint(fields=('code', 'date'), name='unique_index_date')],
            },
        ),
    ]
