# Generated by Django 5.2.3 on 2025-07-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0014_indexohlcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexohlcv',
            name='change',
            field=models.FloatField(default=0.0),
        ),
    ]
