# Generated by Django 5.2.3 on 2025-07-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0015_remove_tradingdefaults_default_strategy_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdefaults',
            name='trading_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('turtle', 'Turtle(ATR)')], default='turtle', max_length=20),
        ),
    ]
