# Generated by manual creation on 2025-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0016_tradingdefaults_trading_mode'),
    ]

    operations = [
        # Remove old fields
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='default_max_loss',
        ),
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='default_stop_loss',
        ),
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='default_take_profit',
        ),
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='default_pyramiding_count',
        ),
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='default_position_size',
        ),
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='use_trailing_stop',
        ),
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='trailing_stop_percent',
        ),
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='pyramiding_entries',
        ),
        
        # Add Manual mode fields
        migrations.AddField(
            model_name='tradingdefaults',
            name='manual_max_loss',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='manual_stop_loss',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='manual_take_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='manual_pyramiding_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='manual_position_size',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='manual_positions',
            field=models.JSONField(blank=True, default=lambda: [100]),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='manual_pyramiding_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='manual_use_trailing_stop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='manual_trailing_stop_percent',
            field=models.FloatField(default=8.0),
        ),
        
        # Add Turtle mode fields
        migrations.AddField(
            model_name='tradingdefaults',
            name='turtle_max_loss',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='turtle_stop_loss',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='turtle_take_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='turtle_pyramiding_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='turtle_position_size',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='turtle_positions',
            field=models.JSONField(blank=True, default=lambda: [25, 25, 25, 25]),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='turtle_pyramiding_entries',
            field=models.JSONField(blank=True, default=lambda: ["", "", ""]),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='turtle_use_trailing_stop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='turtle_trailing_stop_percent',
            field=models.FloatField(default=3.0),
        ),
    ]