# Generated by Django 5.2.3 on 2025-07-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0018_alter_tradingdefaults_manual_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockohlcv',
            name='close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockohlcv',
            name='high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockohlcv',
            name='low',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockohlcv',
            name='open',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockohlcv',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
