# Generated by Django 5.2.3 on 2025-08-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0019_alter_stockohlcv_close_alter_stockohlcv_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='htf_8week_gain',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='htf_current_status',
            field=models.CharField(choices=[('none', '해당 없음'), ('rising', '상승중'), ('pullback', '조정중'), ('breakout', '돌파')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='htf_max_pullback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='htf_pattern_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='htf_pattern_peak_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='htf_pattern_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingconfig',
            name='strategy_type',
            field=models.CharField(choices=[('mtt', 'MTT (Minervini Trend Template)'), ('weekly_high', '52주 신고가'), ('fifty_day_high', '50일 신고가'), ('daily_top50', '일일 Top50'), ('htf', 'High Tight Flag')], default='mtt', max_length=20),
        ),
    ]
