# Generated by Django 5.2.3 on 2025-08-13 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0020_add_htf_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('stock_name', models.CharField(max_length=100)),
                ('first_entry_date', models.DateTimeField(blank=True, null=True)),
                ('last_exit_date', models.DateTimeField(blank=True, null=True)),
                ('total_buy_amount', models.BigIntegerField(default=0)),
                ('total_sell_amount', models.BigIntegerField(default=0)),
                ('total_profit_loss', models.BigIntegerField(default=0)),
                ('profit_loss_percent', models.FloatField(default=0.0)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('holding_days', models.FloatField(default=0.0)),
                ('entry_count', models.IntegerField(default=0)),
                ('exit_count', models.IntegerField(default=0)),
                ('trading_mode', models.CharField(choices=[('manual', 'Manual'), ('turtle', 'Turtle')], max_length=20)),
                ('win_rate', models.FloatField(default=0.0)),
                ('avg_holding_days', models.FloatField(default=0.0)),
                ('max_profit_percent', models.FloatField(blank=True, null=True)),
                ('final_status', models.CharField(choices=[('CLOSED', 'Closed'), ('HOLDING', 'Holding')], max_length=10)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_summary',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'final_status'], name='trading_sum_user_id_75f482_idx'), models.Index(fields=['user', 'trading_mode'], name='trading_sum_user_id_b4189e_idx'), models.Index(fields=['stock_code'], name='trading_sum_stock_c_7266f7_idx')],
                'unique_together': {('user', 'stock_code', 'first_entry_date')},
            },
        ),
    ]
