# Generated by Django 5.2.5 on 2026-04-17 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0021_tradingsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingconfig',
            name='autobot_config_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='autobot_server_ip',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='autobot_server_port',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_connection',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='server_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trading_server_ip',
        ),
        migrations.CreateModel(
            name='TradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('stock_name', models.CharField(max_length=100)),
                ('trade_type', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도')], max_length=10)),
                ('entry_type', models.CharField(choices=[('INITIAL', '최초진입'), ('PYRAMIDING', '피라미딩'), ('EXIT_PARTIAL', '부분청산'), ('EXIT_FULL', '전량청산'), ('STOP_LOSS', '손절'), ('TRAILING_STOP', '트레일링스탑')], default='INITIAL', max_length=20)),
                ('order_no', models.CharField(blank=True, max_length=20)),
                ('order_quantity', models.IntegerField(default=0)),
                ('order_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('filled_quantity', models.IntegerField(default=0)),
                ('filled_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('filled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit_loss_percent', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', '주문접수'), ('FILLED', '체결완료'), ('PARTIAL', '부분체결'), ('CANCELLED', '취소'), ('FAILED', '실패')], default='SUBMITTED', max_length=20)),
                ('atr_value', models.FloatField(blank=True, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='myweb.tradingconfig')),
                ('trading_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='myweb.tradingsummary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_entry',
                'ordering': ['-ordered_at'],
                'indexes': [models.Index(fields=['user', 'stock_code'], name='trade_entry_user_id_294048_idx'), models.Index(fields=['user', 'status'], name='trade_entry_user_id_14171b_idx'), models.Index(fields=['order_no'], name='trade_entry_order_n_9cafef_idx')],
            },
        ),
    ]
