# Generated by Django 5.2.5 on 2026-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0022_remove_tradingconfig_autobot_config_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexohlcv',
            name='close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='indexohlcv',
            name='high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='indexohlcv',
            name='low',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='indexohlcv',
            name='open',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='indexohlcv',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
