# Generated by Django 5.2.5 on 2026-04-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0023_index_ohlcv_float_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['date'], name='idx_stockanalysis_date'),
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['date', 'is_minervini_trend'], name='idx_stockanalysis_date_mtt'),
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['code', '-date'], name='idx_sa_code_date_desc'),
        ),
    ]
