# Generated by Django 5.2.5 on 2026-04-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0024_add_stockanalysis_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdefaults',
            name='manual_max_loss',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='tradingdefaults',
            name='turtle_max_loss',
            field=models.FloatField(default=2.0),
        ),
    ]
