# Generated by Django 5.2.5 on 2026-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0025_update_max_loss_default_to_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shares_outstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
