# Generated by Django 5.2.3 on 2026-04-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0026_add_shares_outstanding_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfig',
            name='trailing_stop_peak_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
