# Generated by Django 5.2.5 on 2026-04-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0027_add_trailing_stop_peak_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdefaults',
            name='manual_trailing_stop_trigger',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='turtle_trailing_stop_trigger',
            field=models.FloatField(default=2.0),
        ),
    ]
