# Generated by Django 5.2.5 on 2026-05-06 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0029_add_staged_exit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_money', models.BigIntegerField(default=0)),
                ('stock_money', models.BigIntegerField(default=0)),
                ('remain_money', models.BigIntegerField(default=0)),
                ('stock_revenue', models.BigIntegerField(default=0)),
                ('confirmed_capital', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_account_snapshot',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
