# Generated by Django 5.2.3 on 2026-05-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0030_dailyaccountsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMinuteOhlcv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=10)),
                ('bar_datetime', models.DateTimeField()),
                ('open', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_minute_ohlcv',
                'ordering': ['stock_code', 'bar_datetime'],
                'indexes': [models.Index(fields=['stock_code', 'bar_datetime'], name='idx_smo_code_dt')],
                'unique_together': {('stock_code', 'bar_datetime')},
            },
        ),
    ]
