# Generated by Django 5.2.5 on 2026-07-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0031_add_stock_minute_ohlcv'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorFlowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('stock_name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('investor_today', models.JSONField(blank=True, default=dict)),
                ('foreign_total', models.JSONField(blank=True, default=dict)),
                ('program_trade', models.JSONField(blank=True, default=dict)),
                ('member_firm', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'stock_code'],
                'unique_together': {('stock_code', 'date')},
            },
        ),
    ]
