# Generated by Django 5.2.5 on 2026-08-19 13:54

import myweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0033_theme_surge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfig',
            name='theme_pullback_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='theme_t_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='theme_trailing_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_exit_stages',
            field=models.JSONField(blank=True, default=myweb.models.default_theme_surge_exit_stages),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_force_exit_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_force_exit_time',
            field=models.TimeField(default=myweb.models.default_theme_surge_force_exit_time),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_max_loss',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_trailing_bar_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_trailing_bar_unit',
            field=models.CharField(choices=[('1m', '1분봉'), ('5m', '5분봉'), ('1d', '일봉')], default='5m', max_length=4),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_trailing_start_t',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_use_own_exit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_use_trailing',
            field=models.BooleanField(default=True),
        ),
    ]
