# Generated by Django 5.2.5 on 2026-08-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0034_tradingconfig_theme_pullback_low_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradingconfig',
            unique_together=set(),
        ),
    ]
