# Generated by Django 5.2.3 on 2026-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0035_alter_tradingconfig_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdefaults',
            name='screener_min_op_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='screener_min_op_profit_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='screener_min_revenue_growth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
