# Generated by Django 5.2.3 on 2026-08-25 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0036_tradingdefaults_screener_min_op_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='KisAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('REAL', '실계좌'), ('VIRTUAL', '가상계좌')], default='VIRTUAL', max_length=10)),
                ('account_no', models.CharField(max_length=20)),
                ('account_cd', models.CharField(default='01', max_length=4)),
                ('encrypted_app_key', models.TextField()),
                ('encrypted_app_secret', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kis_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kis_account',
                'ordering': ['-is_default', 'account_type', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StrategyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(choices=[('mtt', 'MTT (Minervini Trend Template)'), ('weekly_high', '52주 신고가'), ('fifty_day_high', '50일 신고가'), ('daily_top50', '일일 Top50'), ('htf', 'High Tight Flag'), ('theme_surge', '급등테마주')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_assignments', to='myweb.kisaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'strategy_account',
                'ordering': ['strategy_type'],
                'unique_together': {('user', 'strategy_type')},
            },
        ),
    ]
