# Generated by Django 5.2.5 on 2026-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0038_bootstrap_owner_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_max_position_pct',
            field=models.FloatField(default=20.0),
        ),
    ]
