# Generated by Django 5.2.5 on 2026-08-26 13:16

import myweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0039_tradingdefaults_theme_surge_max_position_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_entry_stages',
            field=models.JSONField(blank=True, default=myweb.models.default_theme_surge_entry_stages),
        ),
    ]
