# Generated by Django 5.2.3 on 2026-08-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0040_tradingdefaults_theme_surge_entry_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdefaults',
            name='theme_surge_max_candidates',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='tradingdefaults',
            name='theme_surge_trailing_bar_unit',
            field=models.CharField(choices=[('1m', '1분봉'), ('5m', '5분봉'), ('1d', '일봉')], default='1m', max_length=4),
        ),
        migrations.AlterField(
            model_name='tradingdefaults',
            name='theme_surge_trailing_start_t',
            field=models.FloatField(default=1.5),
        ),
    ]
