# Generated by Django 5.2.3 on 2026-09-07 23:15

import myweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0042_theme_surge_exit_tuning_p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_overnight_conditions',
            field=models.JSONField(blank=True, default=myweb.models.default_theme_surge_overnight_conditions),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_overnight_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_overnight_max_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_overnight_min_count',
            field=models.IntegerField(default=2),
        ),
    ]
