# Generated by Django 5.2.3 on 2026-09-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0043_tradingdefaults_theme_surge_overnight_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeExitSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('checked_at', models.DateTimeField()),
                ('tics_id', models.IntegerField(default=0)),
                ('theme_name', models.CharField(blank=True, max_length=100)),
                ('stock_code', models.CharField(max_length=10)),
                ('stock_name', models.CharField(max_length=100)),
                ('force_exit_time', models.TimeField()),
                ('days_held', models.IntegerField(default=1)),
                ('decision', models.CharField(choices=[('overnight', '익일 이월'), ('force_exit', '당일 강제청산'), ('max_days', '보유기간 만료 청산'), ('stop_loss', '손절 청산'), ('trailing', '트레일링 청산'), ('staged', '분할 익절'), ('hold', '유예/보류')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('overnight_evaluated', models.BooleanField(default=False)),
                ('overnight_available', models.BooleanField(default=False)),
                ('overnight_conditions', models.JSONField(blank=True, default=list)),
                ('overnight_met', models.JSONField(blank=True, default=dict)),
                ('overnight_met_count', models.IntegerField(default=0)),
                ('overnight_required', models.IntegerField(default=0)),
                ('overnight_detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_exit_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'theme_exit_signal',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='idx_txs_user_date')],
                'unique_together': {('user', 'date', 'stock_code')},
            },
        ),
    ]
