# Generated by Django 5.2.5 on 2026-09-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0044_themeexitsignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeexitsignal',
            name='decision',
            field=models.CharField(choices=[('overnight', '익일 이월'), ('force_exit', '당일 강제청산'), ('max_days', '보유기간 만료 청산'), ('stop_loss', '손절 청산'), ('trailing', '트레일링 청산'), ('staged', '분할 익절'), ('hold', '유예/보류'), ('force_exit_failed', '강제청산 실패(가격조회 오류)')], max_length=20),
        ),
    ]
