# Generated by Django 5.2.3 on 2026-09-27 12:15

import myweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0045_alter_themeexitsignal_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeentrysignal',
            name='day_realized_losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themeentrysignal',
            name='day_trade_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themeentrysignal',
            name='gate_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='themeentrysignal',
            name='theme_fluctuation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_daily_max_loss_pct',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_daily_max_losses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_entry_cutoff',
            field=models.TimeField(default=myweb.models.default_theme_surge_entry_cutoff),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_overnight_breakeven_stop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='theme_surge_overnight_min_profit_r',
            field=models.FloatField(default=0.5),
        ),
    ]
