# Generated by Django 5.2.3 on 2025-07-12 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='autobot_server_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='autobot_server_port',
            field=models.IntegerField(default=8080),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_connection',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='server_status',
            field=models.CharField(choices=[('online', '온라인'), ('offline', '오프라인'), ('error', '오류')], default='offline', max_length=20),
        ),
        migrations.CreateModel(
            name='TradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('stock_name', models.CharField(max_length=100)),
                ('trading_mode', models.CharField(choices=[('manual', 'Manual'), ('turtle', 'Turtle(ATR)')], max_length=20)),
                ('max_loss', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('pyramiding_count', models.IntegerField(default=0)),
                ('position_size', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('autobot_config_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'stock_code', 'is_active')},
            },
        ),
        migrations.AddField(
            model_name='tradingresult',
            name='trading_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='myweb.tradingconfig'),
        ),
    ]
