# Generated by Django 5.2.3 on 2025-07-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_userprofile_autobot_server_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingconfig',
            name='max_loss',
        ),
    ]
