# Generated by Django 5.2.3 on 2025-07-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_remove_tradingconfig_max_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfig',
            name='max_loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
