# Generated by Django 5.2.3 on 2025-07-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_tradingconfig_max_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='atrRatio',
            field=models.FloatField(default=0.0),
        ),
    ]
