# Generated by Django 5.2.3 on 2025-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_stockanalysis_atrratio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradingconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tradingconfig',
            name='strategy_type',
            field=models.CharField(choices=[('mtt', 'MTT (Minervini Trend Template)'), ('weekly_high', '52주 신고가')], default='mtt', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tradingconfig',
            unique_together={('user', 'stock_code', 'strategy_type', 'is_active')},
        ),
    ]
