# Generated by Django 5.2.3 on 2025-07-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_tradingconfig_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='max_50d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='max_50d_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='min_50d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='min_50d_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
