# Generated by Django 5.2.3 on 2025-07-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0012_alter_tradingconfig_trading_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='trading_end_time',
        ),
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='trading_start_time',
        ),
    ]
