# Generated by Django 5.2.3 on 2025-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0013_remove_tradingdefaults_trading_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdefaults',
            name='positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tradingdefaults',
            name='pyramiding_entries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
