# Generated by Django 5.2.3 on 2025-07-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0014_tradingdefaults_positions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='default_strategy_type',
        ),
        migrations.RemoveField(
            model_name='tradingdefaults',
            name='default_trading_mode',
        ),
    ]
