# Generated by Django 5.2.3 on 2025-07-29 23:04

import myweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0017_add_separate_manual_turtle_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdefaults',
            name='manual_positions',
            field=models.JSONField(blank=True, default=myweb.models.default_manual_positions),
        ),
        migrations.AlterField(
            model_name='tradingdefaults',
            name='turtle_positions',
            field=models.JSONField(blank=True, default=myweb.models.default_turtle_positions),
        ),
        migrations.AlterField(
            model_name='tradingdefaults',
            name='turtle_pyramiding_entries',
            field=models.JSONField(blank=True, default=myweb.models.default_turtle_pyramiding_entries),
        ),
    ]
