"""
Django settings for dolpha project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import platform
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ophb6jnq-m0ahk(8z&dw9#k1q52gaar8(s16+9-x&t)72*f27='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'myweb',
    'django_apscheduler',
    'corsheaders',
]

# APScheduler 설정
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"  # 관리자 인터페이스에서 표시되는 시간 형식
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # 작업 실행 타임아웃 (초 단위, 필요에 따라 조정)
SCHEDULER_DEFAULT = True  # 앱 시작 시 스케줄러 자동 실행

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 허용된 도메인 목록 (CORS와 CSRF에서 공통 사용)
ALLOWED_FRONTEND_ORIGINS = [
    "http://localhost:3000",  # React 개발 서버
    "http://127.0.0.1:3000",
    "http://218.152.32.218:3000",  # 실제 서버 도메인
    "http://dolpha.iptime.org:3000",  # 실제 서버 도메인
]

# CORS 설정 - credentials를 지원하기 위해 구체적인 도메인 허용
CORS_ALLOWED_ORIGINS = ALLOWED_FRONTEND_ORIGINS
CORS_ALLOW_CREDENTIALS = True  # 쿠키, 인증 헤더 허용

# 허용할 헤더 설정
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF 설정 - 프론트엔드 도메인을 신뢰할 수 있는 출처로 추가
CSRF_TRUSTED_ORIGINS = ALLOWED_FRONTEND_ORIGINS

ROOT_URLCONF = 'dolpha.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dolpha.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dolpha_db',
        'USER': 'dolpha',
        'PASSWORD': 'dolpha123',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# 환경별 데이터베이스 설정
import os
if os.environ.get('DJANGO_DB_HOST'):  # 환경변수로 직접 지정한 경우
    DATABASES['default'].update({
        'HOST': os.environ.get('DJANGO_DB_HOST'),
    })
elif platform.system() in ['Windows', 'Darwin']:  # Windows 또는 macOS
    # 로컬 MariaDB 사용 (localhost), 원격 서버 사용 시 아래 주석 해제
    # DATABASES['default'].update({'HOST': '218.152.32.218'})
    pass  # localhost (기본값) 사용
else:  # Ubuntu (Docker 환경)
    DATABASES['default'].update({
        'HOST': 'mariadb',  # Docker 컨테이너명
        'PORT': 3306,
    })


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'myweb.User'

# Django REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Simple JWT 설정

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
    'TOKEN_VERIFY_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenVerifySerializer',
    'TOKEN_BLACKLIST_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenBlacklistSerializer',
    'SLIDING_TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer',
    'SLIDING_TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer',
}

# Google OAuth 설정
GOOGLE_OAUTH2_CLIENT_ID = '117169175456-hvvdlf539dva9fp2tmbacs4kphnnv1mf.apps.googleusercontent.com'
GOOGLE_OAUTH2_CLIENT_SECRET = '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'

# ─────────────────────────────────────────────────────────────
# KIS(한국투자증권) API 설정
# KIS API 설정 — 실계좌 / 모의계좌 듀얼 지원
# 아래 환경변수를 서버 환경(.env 또는 docker-compose)에 설정하세요.
# ─────────────────────────────────────────────────────────────
# 실계좌 (시세 조회 + 실거래)
KIS_REAL_APP_KEY    = os.environ.get('KIS_REAL_APP_KEY', '')
KIS_REAL_APP_SECRET = os.environ.get('KIS_REAL_APP_SECRET', '')
KIS_REAL_ACCOUNT_NO = os.environ.get('KIS_REAL_ACCOUNT_NO', '')
# 모의계좌 (자동매매 테스트)
KIS_VIRTUAL_APP_KEY    = os.environ.get('KIS_VIRTUAL_APP_KEY', '')
KIS_VIRTUAL_APP_SECRET = os.environ.get('KIS_VIRTUAL_APP_SECRET', '')
KIS_VIRTUAL_ACCOUNT_NO = os.environ.get('KIS_VIRTUAL_ACCOUNT_NO', '')
# 공통
KIS_ACCOUNT_CD = os.environ.get('KIS_ACCOUNT_CD', '01')
KIS_MODE       = os.environ.get('KIS_MODE', 'REAL')   # REAL | VIRTUAL (자동매매 모드)
# KIS_APP_KEY가 설정된 경우 실계좌로 간주 (하위 호환)
KIS_APP_KEY    = KIS_REAL_APP_KEY or os.environ.get('KIS_APP_KEY', '')
